### ISSUE TITLE
PulsePoint and Contextweb

### ISSUE THREAD

**Issue by mrpbennett** [InteractiveAdvertisingBureau/adstxtcrawler#11]
I have noticed within the .sql file PulsePoint and Contextweb are listed under the same ID number (95)

Does this mean if a publisher were to add PulsePoint or add Contextweb into their file, it would be recognised as the same? 

As PulsePoint is Contextweb.

**Comment by iantri** [comment]
Hi Paul,

These are mappings for the purpose of normalization, and reflect observed variants. The most up-to-date version is here:

https://wiki.iabtechlab.com/index.php?title=Ads.txt_Normalization_Mappings

So from there, you can see that PulsePoint is recorded as having a proper canonical domain of "contextweb.com", but nevertheless observed variants are included for mapping so that, by writing a query like that shown on the page, the data can be normalized for ease of use.
