### ISSUE TITLE
Sqlite DB not populating

### ISSUE THREAD

**Issue by tedrand** [InteractiveAdvertisingBureau/adstxtcrawler#17]
I love this tool but for some reason when I run it the data doesn't get stored on the DB I have been just outputting it to a CSV but wondering if I am missing something obvious.

**Comment by zeffdotorg** [comment]
Found the same thing, appears to be due to the CREATE adstxt statement having a NOT NULL column that the script doesn't use.  Commenting out ADSYSTEM_DOMAIN like below in the adstxt_crawler.sql file fixed it for me.
--       ADSYSTEM_DOMAIN		    INTEGER     NOT NULL,
Table populates not but I haven't checked the output.

**Comment by nealrichter** [comment]
fixed.
